### ISSUE TITLE
3rd Assignment

### ISSUE THREAD

**Issue by nykoh2001** [NOW-SOPT-SERVER/NayeonKoh#7]
## Description
블로그 글을 작성하는 POST API,
블로그 글 정보를 조회하는 GET API를 작성합니다.

## Tasks
- [x] project setting
- [x] create post api
- [x] get post api
- [ ] write test code
